In [1]:
!unzip -q -o ./data/you-tube-comments-signal-vsosai.zip -d ./data/

## Dependencies

In [2]:
import pandas as pd
import numpy as np

from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn

import nltk
from nltk.corpus import stopwords

In [3]:
df_train = pd.read_csv('./data/train.csv')
df_train.head()

    id                                       comment_text  target
0   59  Eh c kii ce favoritisme lui il a tou led iphon...       1
1  167  It's a myth that Neanderthals were stupid. The...       1
2  169             Emma is super white.\nIn other news...       1
3  372  Chelsea and Aubrey are my favourite on Teen Mo...       1
4  373  that mustard colour tho 😻😻 p.s absolutely love...       1

## EDA

In [4]:
df_train.shape

(51153, 3)

In [5]:
df_train['target'].value_counts()

target
0    38530
1     7808
2     3125
3     1690
Name: count, dtype: int64

In [6]:
df_train['comment_text'][:10]

0    Eh c kii ce favoritisme lui il a tou led iphon...
1    It's a myth that Neanderthals were stupid. The...
2               Emma is super white.\nIn other news...
3    Chelsea and Aubrey are my favourite on Teen Mo...
4    that mustard colour tho 😻😻 p.s absolutely love...
5    OMG u tagged Dina, never see anyone mention he...
6    when you said you're girl twins would be calle...
7                                 Loved this lousie♥♥♥
8    I'm a man united fan but anyone who can't see ...
9    When Christensen speaks better English than Ro...
Name: comment_text, dtype: object

In [7]:
df_train.isna().sum()

id              0
comment_text    9
target          0
dtype: int64

In [8]:
df_train = df_train.fillna("NA")

## Solutions

In [9]:
X = df_train.drop(columns=['id', 'target'])
y = df_train['target']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [10]:
X_train

                                            comment_text
29554                                         Fuck life.
44479                                             woooow
28131                                   This so so funny
41042                                                  H
34839                                                 Hi
...                                                  ...
8444        Clark Gable and George Clooney look the same
31718                               The chef is french ?
9697   Pink's reaction would totally be my reaction. ...
37972                                     ONE HOUR LATER
7374              True, demi is better than Taylor swift

[40922 rows x 1 columns]

### CatBoost

In [19]:
model = CatBoostClassifier(
    iterations=100,
    # learning_rate=0.1,
    eval_metric='MultiClass',
    random_seed=42,
    early_stopping_rounds=100,
    use_best_model=True,
    thread_count=-1,
    auto_class_weights='Balanced'
)

model.fit(
    X_train,
    y_train,
    text_features=['comment_text'],
    eval_set=(X_val, y_val),
    verbose=100
)

Learning rate set to 0.116297
0:	learn: 1.2822748	test: 1.2582531	best: 1.2582531 (0)	total: 432ms	remaining: 7m 11s

KeyboardInterrupt: