In [1]:
!unzip -q -o ./data/you-tube-comments-signal-vsosai.zip -d ./data/

In [1]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

## Dependencies

In [2]:
import pandas as pd
import numpy as np

from catboost import CatBoostClassifier

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler

import matplotlib.pyplot as plt
import seaborn

import emoji

from tqdm.cli import tqdm
from tqdm import trange

tqdm.pandas()

import string

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('averaged_perceptron_tagger', quiet=True)
nltk.download('averaged_perceptron_tagger_eng', quiet=True)
nltk.download('names', quiet=True)

True

In [3]:
df_train = pd.read_csv('./data/train.csv')
df_test = pd.read_csv('./data/test.csv')
df_train.head()

    id                                       comment_text  target
0   59  Eh c kii ce favoritisme lui il a tou led iphon...       1
1  167  It's a myth that Neanderthals were stupid. The...       1
2  169             Emma is super white.\nIn other news...       1
3  372  Chelsea and Aubrey are my favourite on Teen Mo...       1
4  373  that mustard colour tho 😻😻 p.s absolutely love...       1

## EDA

In [4]:
df_train.shape

(51153, 3)

In [5]:
df_train['target'].value_counts()

target
0    38530
1     7808
2     3125
3     1690
Name: count, dtype: int64

In [6]:
df_train['comment_text'][:10]

0    Eh c kii ce favoritisme lui il a tou led iphon...
1    It's a myth that Neanderthals were stupid. The...
2               Emma is super white.\nIn other news...
3    Chelsea and Aubrey are my favourite on Teen Mo...
4    that mustard colour tho 😻😻 p.s absolutely love...
5    OMG u tagged Dina, never see anyone mention he...
6    when you said you're girl twins would be calle...
7                                 Loved this lousie♥♥♥
8    I'm a man united fan but anyone who can't see ...
9    When Christensen speaks better English than Ro...
Name: comment_text, dtype: object

In [7]:
df_train.isna().sum()

id              0
comment_text    9
target          0
dtype: int64

In [8]:
df_train = df_train.fillna("NA")
df_test = df_test.fillna("NA")

## Solutions

In [9]:
def text_feature_extraction(df: pd.DataFrame, col: str):
    df['emoji_count'] = df[col].progress_apply(lambda x: len(emoji.emoji_list(x)))
    df['happy'] = df[col].progress_apply(lambda x: x.count(':)') + x.count(';)') + x.count('(:') + x.count('(;'))
    df['sad'] = df[col].progress_apply(lambda x: x.count(':(') + x.count(';(') + x.count('):') + x.count(');'))
    df['is_na'] = df[col] == "NA"
    return df

In [10]:
df_train = text_feature_extraction(df_train, 'comment_text')
df_test = text_feature_extraction(df_test, 'comment_text')

100%|██████████| 51153/51153 [00:01<00:00, 45662.47it/s]
100%|██████████| 51153/51153 [00:00<00:00, 1349624.98it/s]
100%|██████████| 51153/51153 [00:00<00:00, 1357936.38it/s]
100%|██████████| 15050/15050 [00:00<00:00, 47813.02it/s]
100%|██████████| 15050/15050 [00:00<00:00, 1373013.05it/s]
100%|██████████| 15050/15050 [00:00<00:00, 1337718.81it/s]

### CatBoost

In [11]:
X = df_train.drop(columns=['id', 'target'])
y = df_train['target']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [12]:
model = CatBoostClassifier(
    iterations=50000,
    learning_rate=0.01,
    eval_metric='MultiClass',
    random_seed=42,
    early_stopping_rounds=1000,
    use_best_model=True,
    thread_count=-1,
    task_type='GPU',
    auto_class_weights='Balanced',
    text_features=['comment_text']
)

model.fit(
   X_train,
   y_train,
   eval_set=(X_val, y_val),
   verbose=1000
)

0:	learn: 1.3757626	test: 1.3736035	best: 1.3736035 (0)	total: 7.57ms	remaining: 6m 18s
1000:	learn: 0.6741123	test: 0.5871296	best: 0.5871296 (1000)	total: 3.83s	remaining: 3m 7s
2000:	learn: 0.6147511	test: 0.5497797	best: 0.5497797 (2000)	total: 7.37s	remaining: 2m 56s
3000:	learn: 0.5744478	test: 0.5290956	best: 0.5290956 (3000)	total: 10.9s	remaining: 2m 50s
4000:	learn: 0.5438920	test: 0.5145723	best: 0.5145723 (4000)	total: 14.4s	remaining: 2m 45s
5000:	learn: 0.5184076	test: 0.5032320	best: 0.5032303 (4999)	total: 18s	remaining: 2m 41s
6000:	learn: 0.4968722	test: 0.4943451	best: 0.4943451 (6000)	total: 21.5s	remaining: 2m 37s
7000:	learn: 0.4774578	test: 0.4866584	best: 0.4866584 (7000)	total: 25.1s	remaining: 2m 34s
8000:	learn: 0.4604637	test: 0.4800477	best: 0.4800477 (8000)	total: 28.6s	remaining: 2m 30s
9000:	learn: 0.4450564	test: 0.4741294	best: 0.4741256 (8998)	total: 32.2s	remaining: 2m 26s
10000:	learn: 0.4308684	test: 0.4692514	best: 0.4692514 (10000)	total: 35.7s	remaining: 2m 22s
11000:	learn: 0.4182010	test: 0.4648866	best: 0.4648866 (11000)	total: 39.2s	remaining: 2m 18s
12000:	learn: 0.4062559	test: 0.4605623	best: 0.4605623 (12000)	total: 42.7s	remaining: 2m 15s
13000:	learn: 0.3953145	test: 0.4569371	best: 0.4569371 (13000)	total: 46.2s	remaining: 2m 11s
14000:	learn: 0.3851718	test: 0.4535127	best: 0.4535120 (13999)	total: 49.7s	remaining: 2m 7s
15000:	learn: 0.3756335	test: 0.4504010	best: 0.4504010 (15000)	total: 53.2s	remaining: 2m 4s
16000:	learn: 0.3666206	test: 0.4475422	best: 0.4475422 (16000)	total: 56.7s	remaining: 2m
17000:	learn: 0.3579491	test: 0.4447274	best: 0.4447274 (17000)	total: 1m	remaining: 1m 56s
18000:	learn: 0.3499058	test: 0.4424090	best: 0.4424090 (18000)	total: 1m 3s	remaining: 1m 53s
19000:	learn: 0.3423575	test: 0.4402664	best: 0.4402635 (18982)	total: 1m 7s	remaining: 1m 49s
20000:	learn: 0.3351161	test: 0.4383353	best: 0.4383353 (20000)	total: 1m 10s	remaining: 1m 46s
21000:	learn: 0.3283294	test: 0.4363617	best: 0.4363617 (21000)	total: 1m 14s	remaining: 1m 42s
22000:	learn: 0.3218702	test: 0.4347282	best: 0.4347242 (21993)	total: 1m 17s	remaining: 1m 39s
23000:	learn: 0.3157431	test: 0.4331446	best: 0.4331369 (22987)	total: 1m 21s	remaining: 1m 35s
24000:	learn: 0.3097386	test: 0.4317209	best: 0.4317206 (23997)	total: 1m 24s	remaining: 1m 31s
25000:	learn: 0.3040781	test: 0.4305334	best: 0.4305334 (25000)	total: 1m 28s	remaining: 1m 28s
26000:	learn: 0.2986559	test: 0.4294893	best: 0.4294893 (26000)	total: 1m 31s	remaining: 1m 24s
27000:	learn: 0.2934385	test: 0.4282047	best: 0.4282036 (26999)	total: 1m 35s	remaining: 1m 21s
28000:	learn: 0.2884477	test: 0.4272872	best: 0.4272629 (27975)	total: 1m 39s	remaining: 1m 17s
29000:	learn: 0.2837006	test: 0.4263299	best: 0.4263042 (28992)	total: 1m 42s	remaining: 1m 14s
30000:	learn: 0.2791345	test: 0.4255559	best: 0.4255544 (29999)	total: 1m 46s	remaining: 1m 10s
31000:	learn: 0.2746928	test: 0.4246762	best: 0.4246640 (30993)	total: 1m 49s	remaining: 1m 7s
32000:	learn: 0.2704877	test: 0.4240281	best: 0.4240281 (32000)	total: 1m 53s	remaining: 1m 3s
33000:	learn: 0.2665092	test: 0.4234908	best: 0.4234435 (32920)	total: 1m 56s	remaining: 1m
34000:	learn: 0.2625096	test: 0.4228743	best: 0.4228606 (33960)	total: 2m	remaining: 56.7s
35000:	learn: 0.2586307	test: 0.4222331	best: 0.4222176 (34985)	total: 2m 3s	remaining: 53.1s
36000:	learn: 0.2549046	test: 0.4217218	best: 0.4217218 (36000)	total: 2m 7s	remaining: 49.6s
37000:	learn: 0.2513513	test: 0.4211724	best: 0.4211724 (37000)	total: 2m 10s	remaining: 46s
38000:	learn: 0.2478552	test: 0.4207070	best: 0.4206878 (37964)	total: 2m 14s	remaining: 42.5s
39000:	learn: 0.2444528	test: 0.4204437	best: 0.4204239 (38972)	total: 2m 18s	remaining: 38.9s
40000:	learn: 0.2411331	test: 0.4201641	best: 0.4201641 (40000)	total: 2m 21s	remaining: 35.4s
41000:	learn: 0.2380198	test: 0.4200151	best: 0.4200104 (40575)	total: 2m 25s	remaining: 31.9s
42000:	learn: 0.2348966	test: 0.4196294	best: 0.4196214 (41858)	total: 2m 28s	remaining: 28.3s
43000:	learn: 0.2318826	test: 0.4194940	best: 0.4194597 (42838)	total: 2m 32s	remaining: 24.8s
44000:	learn: 0.2289574	test: 0.4193138	best: 0.4193049 (43988)	total: 2m 35s	remaining: 21.2s
45000:	learn: 0.2261011	test: 0.4192383	best: 0.4192110 (44927)	total: 2m 39s	remaining: 17.7s
46000:	learn: 0.2233831	test: 0.4192028	best: 0.4191654 (45293)	total: 2m 42s	remaining: 14.2s
47000:	learn: 0.2206901	test: 0.4191362	best: 0.4191148 (46987)	total: 2m 46s	remaining: 10.6s
48000:	learn: 0.2181118	test: 0.4191553	best: 0.4190660 (47269)	total: 2m 50s	remaining: 7.08s
bestTest = 0.4190659925
bestIteration = 47269
Shrink model to first 47270 iterations.

CatBoostClassifier(auto_class_weights='Balanced', early_stopping_rounds=1000, eval_metric='MultiClass', iterations=50000, learning_rate=0.01, random_seed=42, task_type='GPU', text_features=['comment_text'], use_best_model=True)

In [13]:
subm = df_test.copy()
subm['target'] = model.predict(df_test.drop(columns=['id']))
subm[['id', 'target']].to_csv("subm.csv", index=False)
subm.head()

,id,comment_text,emoji_count,happy,sad,is_na,target
0,200,Me with Arabic. I can never have a conversatio...,0,0,0,False,2
1,607,if I could subscribe to Dude Perfect a million...,0,0,0,False,1
2,1100,We can fortunately say that we lived in the er...,1,0,0,False,1
3,1137,"Not an easy Classic to cover, you and your ban...",0,0,0,False,1
4,1139,"I really really really love this cover, hope H...",0,0,0,False,1

### Linear Models

#### Data preparing

In [14]:
df_train.head()

,id,comment_text,target,emoji_count,happy,sad,is_na
0,59,Eh c kii ce favoritisme lui il a tou led iphon...,1,0,0,0,False
1,167,It's a myth that Neanderthals were stupid. The...,1,0,0,0,False
2,169,Emma is super white.\nIn other news...,1,0,0,0,False
3,372,Chelsea and Aubrey are my favourite on Teen Mo...,1,4,0,0,False
4,373,that mustard colour tho 😻😻 p.s absolutely love...,1,2,1,0,False

In [15]:
df_extra = pd.read_csv('./data/extra_unlabeled.csv').dropna()

In [16]:
def text_normalize(text: str):
    text = text.lower()
    text = text.replace('\n', ' ')
    text = text.replace('\r', ' ')
    text = text.replace('\t', ' ')
    text = "".join([ch for ch in text if ch not in string.punctuation])
    text = emoji.replace_emoji(text, replace='')

    words = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]
    
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    text = ' '.join(words)
    return text
    
text_normalize(df_train['comment_text'][4])

'mustard colour tho ps absolut love video whenev someon mention babi name instantli think sim okayyyyy'

In [17]:
df_train_clean = df_train.copy()
df_test_clean = df_test.copy()
df_extra_clean = df_extra.copy()

# df_train_clean = text_feature_extraction(df_train_clean, 'comment_text')
df_train_clean['comment_text'] = df_train_clean['comment_text'].progress_apply(text_normalize)

# df_test_clean = text_feature_extraction(df_test_clean, 'comment_text')
df_test_clean['comment_text'] = df_test_clean['comment_text'].progress_apply(text_normalize)

# df_extra_clean = text_feature_extraction(df_extra_clean, 'comment_text')
df_extra_clean['comment_text'] = df_extra_clean['comment_text'].progress_apply(text_normalize)

df_train_clean.head()

  1%|          | 404/51153 [00:00<00:12, 4037.41it/s]

100%|██████████| 51153/51153 [00:08<00:00, 6284.28it/s]
100%|██████████| 15050/15050 [00:02<00:00, 6406.08it/s]
100%|██████████| 652233/652233 [02:01<00:00, 5375.90it/s]

,id,comment_text,target,emoji_count,happy,sad,is_na
0,59,eh c kii ce favoritism lui il tou led iphon ap...,1,0,0,0,False
1,167,myth neanderth stupid actual brainpow human ti...,1,0,0,0,False
2,169,emma super whitenin news,1,0,0,0,False
3,372,chelsea aubrey favourit teen mom well especi c...,1,4,0,0,False
4,373,mustard colour tho ps absolut love video whene...,1,2,1,0,False

In [18]:
all_text = df_train_clean['comment_text'].tolist() + df_extra_clean['comment_text'].tolist() + df_test_clean['comment_text'].tolist()
all_text[:10]

['eh c kii ce favoritism lui il tou led iphon appl watch ipad macbook en avanc est gratuit wallah je reflechi une ide poir wow ador je sui rich mdrr sa arrivera qau autr',
 'myth neanderth stupid actual brainpow human time got assimil',
 'emma super whitenin news',
 'chelsea aubrey favourit teen mom well especi cole babi',
 'mustard colour tho ps absolut love video whenev someon mention babi name instantli think sim okayyyyy',
 'omg u tag dina never see anyon mention even though she amaz',
 'said your girl twin would call lyla luci sister liter look like omg name lyla',
 'love lousi',
 'im man unit fan anyon cant see hazard best player prem last season mad',
 'christensen speak better english rooney']

In [19]:
tfidf = TfidfVectorizer(max_features=20000, ngram_range=(1, 3), stop_words='english')
tfidf.fit(all_text)

TfidfVectorizer(max_features=20000, ngram_range=(1, 3), stop_words='english')

In [20]:
X_tfidf = tfidf.transform(df_train_clean['comment_text'])
X_tfidf_test = tfidf.transform(df_test_clean['comment_text'])
y = df_train_clean['target']

X_tfidf_train, X_tfidf_val, y_train, y_val = train_test_split(X_tfidf, y, test_size=0.3, random_state=42, stratify=y)

# svd = TruncatedSVD(n_components=2000, random_state=42)
# X_tfidf_train = svd.fit_transform(X_tfidf_train)
# X_tfidf_val = svd.transform(X_tfidf_val)
# X_tfidf_test = svd.transform(X_tfidf_test)

# sc = StandardScaler()
# X_tfidf_train = sc.fit_transform(X_tfidf_train)
# X_tfidf_val = sc.transform(X_tfidf_val)
# X_tfidf_test = sc.transform(X_tfidf_test)

print(f"TF-IDF матрица: {X_tfidf.shape}")
print(f"Ненулевых элементов: {X_tfidf.nonzero()[0].shape[0] / np.prod(X_tfidf.shape) * 100:.2f}%")

TF-IDF матрица: (51153, 20000)
Ненулевых элементов: 0.03%

In [21]:
df_test.shape, df_test_clean.shape, X_tfidf_test.shape

((15050, 6), (15050, 6), (15050, 20000))

In [22]:
model = LogisticRegression(
    max_iter=10000,
    n_jobs=-1,
    class_weight='balanced',
    random_state=42
)
# model.fit(X_tfidf_train, y_train)

# y_pred = model.predict(X_tfidf_val)
# f1_score(y_val, y_pred, average='macro')

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, X_tfidf, y, cv=cv, scoring='f1_macro', n_jobs=-1)
scores.mean()

np.float64(0.6719993202435123)

In [23]:
# subm = df_test.copy()
# subm['target'] = model.predict(X_tfidf_test)
# subm.head()

# subm[['id', 'target']].to_csv("subm.csv", index=False)

In [24]:
model = LogisticRegression(
    max_iter=1000000,
    class_weight='balanced',
    n_jobs=-1,
    random_state=42
)
model.fit(X_tfidf_train, y_train)

y_pred = model.predict(X_tfidf_val)
f1_score(y_val, y_pred, average='macro')

0.6673475445853532

In [25]:
subm = df_test.copy()
subm['target'] = model.predict(X_tfidf_test)
subm.head()

subm[['id', 'target']].to_csv("subm.csv", index=False)

In [39]:
model = CatBoostClassifier(
    iterations=10000,
    learning_rate=0.01,
    eval_metric='MultiClass',
    random_seed=42,
    early_stopping_rounds=100,
    use_best_model=True,
    thread_count=-1,
    auto_class_weights='Balanced',
    task_type="GPU"
)

model.fit(
    X_tfidf_train,
    y_train,
    eval_set=(X_tfidf_val, y_val),
    verbose=100
)

0:	learn: 1.3826116	test: 1.3828365	best: 1.3828365 (0)	total: 27ms	remaining: 4m 29s
100:	learn: 1.1651951	test: 1.1873408	best: 1.1873408 (100)	total: 2.31s	remaining: 3m 46s
200:	learn: 1.0550888	test: 1.0966847	best: 1.0966847 (200)	total: 4.53s	remaining: 3m 40s
300:	learn: 0.9805367	test: 1.0363556	best: 1.0363556 (300)	total: 6.72s	remaining: 3m 36s
400:	learn: 0.9222799	test: 0.9891014	best: 0.9891014 (400)	total: 8.9s	remaining: 3m 32s
500:	learn: 0.8753346	test: 0.9518569	best: 0.9518569 (500)	total: 11.1s	remaining: 3m 29s
600:	learn: 0.8357124	test: 0.9202472	best: 0.9202472 (600)	total: 13.2s	remaining: 3m 26s
700:	learn: 0.8007054	test: 0.8931313	best: 0.8931313 (700)	total: 15.4s	remaining: 3m 23s
800:	learn: 0.7704980	test: 0.8692652	best: 0.8692652 (800)	total: 17.5s	remaining: 3m 20s
900:	learn: 0.7435356	test: 0.8479116	best: 0.8479116 (900)	total: 19.6s	remaining: 3m 18s
1000:	learn: 0.7197629	test: 0.8294921	best: 0.8294921 (1000)	total: 21.7s	remaining: 3m 15s
1100:	learn: 0.6974764	test: 0.8124685	best: 0.8124685 (1100)	total: 23.8s	remaining: 3m 12s
1200:	learn: 0.6780334	test: 0.7976051	best: 0.7976051 (1200)	total: 25.9s	remaining: 3m 9s
1300:	learn: 0.6585942	test: 0.7832005	best: 0.7832005 (1300)	total: 28s	remaining: 3m 7s
1400:	learn: 0.6410111	test: 0.7700460	best: 0.7700460 (1400)	total: 30.1s	remaining: 3m 4s
1500:	learn: 0.6245860	test: 0.7582151	best: 0.7582151 (1500)	total: 32.2s	remaining: 3m 2s
1600:	learn: 0.6094631	test: 0.7472164	best: 0.7472164 (1600)	total: 34.3s	remaining: 2m 59s
1700:	learn: 0.5950960	test: 0.7367529	best: 0.7367529 (1700)	total: 36.4s	remaining: 2m 57s
1800:	learn: 0.5814692	test: 0.7264860	best: 0.7264860 (1800)	total: 38.5s	remaining: 2m 55s
1900:	learn: 0.5681249	test: 0.7170672	best: 0.7170672 (1900)	total: 40.6s	remaining: 2m 53s
2000:	learn: 0.5554224	test: 0.7077427	best: 0.7077427 (2000)	total: 42.7s	remaining: 2m 50s
2100:	learn: 0.5436693	test: 0.6993446	best: 0.6993446 (2100)	total: 44.8s	remaining: 2m 48s
2200:	learn: 0.5319063	test: 0.6912308	best: 0.6912308 (2200)	total: 47s	remaining: 2m 46s
2300:	learn: 0.5210316	test: 0.6835488	best: 0.6835488 (2300)	total: 49.1s	remaining: 2m 44s
2400:	learn: 0.5106511	test: 0.6764039	best: 0.6764039 (2400)	total: 51.2s	remaining: 2m 41s
2500:	learn: 0.5007427	test: 0.6697609	best: 0.6697609 (2500)	total: 53.3s	remaining: 2m 39s
2600:	learn: 0.4916877	test: 0.6636813	best: 0.6636813 (2600)	total: 55.4s	remaining: 2m 37s
2700:	learn: 0.4826989	test: 0.6577110	best: 0.6577110 (2700)	total: 57.5s	remaining: 2m 35s
2800:	learn: 0.4736820	test: 0.6515351	best: 0.6515351 (2800)	total: 59.6s	remaining: 2m 33s
2900:	learn: 0.4652165	test: 0.6460419	best: 0.6460419 (2900)	total: 1m 1s	remaining: 2m 30s
3000:	learn: 0.4569726	test: 0.6407088	best: 0.6407088 (3000)	total: 1m 3s	remaining: 2m 28s
3100:	learn: 0.4492719	test: 0.6358052	best: 0.6358052 (3100)	total: 1m 5s	remaining: 2m 26s
3200:	learn: 0.4415510	test: 0.6308505	best: 0.6308505 (3200)	total: 1m 7s	remaining: 2m 24s
3300:	learn: 0.4344134	test: 0.6262228	best: 0.6262228 (3300)	total: 1m 10s	remaining: 2m 22s
3400:	learn: 0.4275193	test: 0.6216531	best: 0.6216531 (3400)	total: 1m 12s	remaining: 2m 20s
3500:	learn: 0.4210741	test: 0.6175197	best: 0.6175197 (3500)	total: 1m 14s	remaining: 2m 17s
3600:	learn: 0.4148353	test: 0.6134113	best: 0.6134113 (3600)	total: 1m 16s	remaining: 2m 15s
3700:	learn: 0.4085707	test: 0.6095801	best: 0.6095801 (3700)	total: 1m 18s	remaining: 2m 13s
3800:	learn: 0.4023150	test: 0.6058642	best: 0.6058642 (3800)	total: 1m 20s	remaining: 2m 11s
3900:	learn: 0.3962970	test: 0.6021704	best: 0.6021704 (3900)	total: 1m 22s	remaining: 2m 9s
4000:	learn: 0.3908499	test: 0.5988412	best: 0.5988412 (4000)	total: 1m 24s	remaining: 2m 6s
4100:	learn: 0.3855885	test: 0.5955581	best: 0.5955581 (4100)	total: 1m 26s	remaining: 2m 4s
4200:	learn: 0.3800067	test: 0.5920697	best: 0.5920697 (4200)	total: 1m 28s	remaining: 2m 2s
4300:	learn: 0.3747890	test: 0.5889074	best: 0.5889074 (4300)	total: 1m 30s	remaining: 2m
4400:	learn: 0.3697979	test: 0.5860589	best: 0.5860589 (4400)	total: 1m 32s	remaining: 1m 58s
4500:	learn: 0.3649814	test: 0.5831423	best: 0.5831423 (4500)	total: 1m 35s	remaining: 1m 56s
4600:	learn: 0.3602681	test: 0.5803033	best: 0.5803033 (4600)	total: 1m 37s	remaining: 1m 53s
4700:	learn: 0.3558351	test: 0.5777605	best: 0.5777605 (4700)	total: 1m 39s	remaining: 1m 51s
4800:	learn: 0.3513445	test: 0.5751512	best: 0.5751512 (4800)	total: 1m 41s	remaining: 1m 49s
4900:	learn: 0.3471116	test: 0.5726767	best: 0.5726767 (4900)	total: 1m 43s	remaining: 1m 47s
5000:	learn: 0.3428684	test: 0.5702863	best: 0.5702863 (5000)	total: 1m 45s	remaining: 1m 45s
5100:	learn: 0.3388307	test: 0.5680166	best: 0.5680166 (5100)	total: 1m 47s	remaining: 1m 43s
5200:	learn: 0.3350005	test: 0.5660058	best: 0.5660058 (5200)	total: 1m 49s	remaining: 1m 40s
5300:	learn: 0.3313811	test: 0.5640227	best: 0.5640227 (5300)	total: 1m 51s	remaining: 1m 38s
5400:	learn: 0.3277880	test: 0.5618290	best: 0.5618266 (5399)	total: 1m 53s	remaining: 1m 36s
5500:	learn: 0.3240955	test: 0.5597999	best: 0.5597999 (5500)	total: 1m 55s	remaining: 1m 34s
5600:	learn: 0.3204842	test: 0.5578230	best: 0.5578230 (5600)	total: 1m 57s	remaining: 1m 32s
5700:	learn: 0.3170951	test: 0.5558905	best: 0.5558905 (5700)	total: 1m 59s	remaining: 1m 30s
5800:	learn: 0.3135683	test: 0.5540334	best: 0.5540334 (5800)	total: 2m 1s	remaining: 1m 28s
5900:	learn: 0.3103211	test: 0.5522488	best: 0.5522488 (5900)	total: 2m 3s	remaining: 1m 25s
6000:	learn: 0.3072386	test: 0.5506918	best: 0.5506918 (6000)	total: 2m 5s	remaining: 1m 23s
6100:	learn: 0.3042466	test: 0.5492291	best: 0.5492291 (6100)	total: 2m 7s	remaining: 1m 21s
6200:	learn: 0.3012141	test: 0.5477038	best: 0.5477038 (6200)	total: 2m 9s	remaining: 1m 19s
6300:	learn: 0.2983019	test: 0.5461579	best: 0.5461579 (6300)	total: 2m 11s	remaining: 1m 17s
6400:	learn: 0.2953779	test: 0.5447540	best: 0.5447540 (6400)	total: 2m 13s	remaining: 1m 15s
6500:	learn: 0.2925943	test: 0.5432210	best: 0.5432210 (6500)	total: 2m 15s	remaining: 1m 13s
6600:	learn: 0.2898194	test: 0.5418159	best: 0.5418159 (6600)	total: 2m 17s	remaining: 1m 10s
6700:	learn: 0.2872166	test: 0.5405615	best: 0.5405615 (6700)	total: 2m 19s	remaining: 1m 8s
6800:	learn: 0.2845456	test: 0.5392452	best: 0.5392452 (6800)	total: 2m 21s	remaining: 1m 6s
6900:	learn: 0.2820289	test: 0.5380188	best: 0.5380188 (6900)	total: 2m 23s	remaining: 1m 4s
7000:	learn: 0.2794888	test: 0.5368869	best: 0.5368869 (7000)	total: 2m 25s	remaining: 1m 2s
7100:	learn: 0.2770884	test: 0.5357945	best: 0.5357945 (7100)	total: 2m 27s	remaining: 1m
7200:	learn: 0.2746706	test: 0.5346550	best: 0.5346550 (7200)	total: 2m 29s	remaining: 58.2s
7300:	learn: 0.2723842	test: 0.5336291	best: 0.5336291 (7300)	total: 2m 31s	remaining: 56.1s
7400:	learn: 0.2701509	test: 0.5326176	best: 0.5326176 (7400)	total: 2m 33s	remaining: 54s
7500:	learn: 0.2679426	test: 0.5315477	best: 0.5315477 (7500)	total: 2m 35s	remaining: 51.9s
7600:	learn: 0.2657667	test: 0.5304919	best: 0.5304919 (7600)	total: 2m 37s	remaining: 49.8s
7700:	learn: 0.2636691	test: 0.5295461	best: 0.5295461 (7700)	total: 2m 39s	remaining: 47.7s
7800:	learn: 0.2616781	test: 0.5287093	best: 0.5287067 (7799)	total: 2m 41s	remaining: 45.6s
7900:	learn: 0.2597658	test: 0.5279453	best: 0.5279453 (7900)	total: 2m 43s	remaining: 43.5s
8000:	learn: 0.2576854	test: 0.5270563	best: 0.5270563 (8000)	total: 2m 45s	remaining: 41.4s
8100:	learn: 0.2558012	test: 0.5261672	best: 0.5261672 (8100)	total: 2m 47s	remaining: 39.3s
8200:	learn: 0.2538664	test: 0.5251651	best: 0.5251651 (8200)	total: 2m 49s	remaining: 37.2s
8300:	learn: 0.2520742	test: 0.5245104	best: 0.5245104 (8300)	total: 2m 51s	remaining: 35.1s
8400:	learn: 0.2502449	test: 0.5236209	best: 0.5236209 (8400)	total: 2m 53s	remaining: 33s
8500:	learn: 0.2484861	test: 0.5228849	best: 0.5228849 (8500)	total: 2m 55s	remaining: 30.9s
8600:	learn: 0.2467471	test: 0.5221254	best: 0.5221254 (8600)	total: 2m 57s	remaining: 28.8s
8700:	learn: 0.2451322	test: 0.5214710	best: 0.5214710 (8700)	total: 2m 59s	remaining: 26.7s
8800:	learn: 0.2434449	test: 0.5207809	best: 0.5207787 (8799)	total: 3m 1s	remaining: 24.7s
8900:	learn: 0.2418578	test: 0.5200398	best: 0.5200398 (8900)	total: 3m 2s	remaining: 22.6s
9000:	learn: 0.2401709	test: 0.5192763	best: 0.5192763 (9000)	total: 3m 4s	remaining: 20.5s
9100:	learn: 0.2386967	test: 0.5187816	best: 0.5187816 (9100)	total: 3m 6s	remaining: 18.5s
9200:	learn: 0.2370827	test: 0.5181389	best: 0.5181389 (9200)	total: 3m 8s	remaining: 16.4s
9300:	learn: 0.2355553	test: 0.5176222	best: 0.5176222 (9300)	total: 3m 10s	remaining: 14.3s
9400:	learn: 0.2341205	test: 0.5169979	best: 0.5169953 (9399)	total: 3m 12s	remaining: 12.3s
9500:	learn: 0.2326230	test: 0.5165179	best: 0.5165174 (9493)	total: 3m 14s	remaining: 10.2s
9600:	learn: 0.2312382	test: 0.5158931	best: 0.5158931 (9600)	total: 3m 16s	remaining: 8.16s
9700:	learn: 0.2298119	test: 0.5151841	best: 0.5151841 (9700)	total: 3m 18s	remaining: 6.11s
9800:	learn: 0.2284388	test: 0.5146377	best: 0.5146377 (9800)	total: 3m 20s	remaining: 4.07s
9900:	learn: 0.2271538	test: 0.5141449	best: 0.5141449 (9900)	total: 3m 22s	remaining: 2.02s
9999:	learn: 0.2257777	test: 0.5136041	best: 0.5136040 (9998)	total: 3m 24s	remaining: 0us
bestTest = 0.5136040469
bestIteration = 9998
Shrink model to first 9999 iterations.

CatBoostClassifier(auto_class_weights='Balanced', early_stopping_rounds=100, eval_metric='MultiClass', iterations=10000, learning_rate=0.01, random_seed=42, task_type='GPU', use_best_model=True)

In [40]:
subm = df_test.copy()
subm['target'] = model.predict(X_tfidf_test)
subm.head()

subm[['id', 'target']].to_csv("subm.csv", index=False)