In [ ]:
!unzip -q -o ./data/you-tube-comments-signal-vsosai.zip -d ./data/

## Dependencies

In [20]:
import pandas as pd
import numpy as np

from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn

import nltk
from nltk.corpus import stopwords

In [21]:
df_train = pd.read_csv('./data/train.csv')
df_test = pd.read_csv('./data/test.csv')
df_train.head()

    id                                       comment_text  target
0   59  Eh c kii ce favoritisme lui il a tou led iphon...       1
1  167  It's a myth that Neanderthals were stupid. The...       1
2  169             Emma is super white.\nIn other news...       1
3  372  Chelsea and Aubrey are my favourite on Teen Mo...       1
4  373  that mustard colour tho 😻😻 p.s absolutely love...       1

## EDA

In [3]:
df_train.shape

(51153, 3)

In [4]:
df_train['target'].value_counts()

target
0    38530
1     7808
2     3125
3     1690
Name: count, dtype: int64

In [5]:
df_train['comment_text'][:10]

0    Eh c kii ce favoritisme lui il a tou led iphon...
1    It's a myth that Neanderthals were stupid. The...
2               Emma is super white.\nIn other news...
3    Chelsea and Aubrey are my favourite on Teen Mo...
4    that mustard colour tho 😻😻 p.s absolutely love...
5    OMG u tagged Dina, never see anyone mention he...
6    when you said you're girl twins would be calle...
7                                 Loved this lousie♥♥♥
8    I'm a man united fan but anyone who can't see ...
9    When Christensen speaks better English than Ro...
Name: comment_text, dtype: object

In [6]:
df_train.isna().sum()

id              0
comment_text    9
target          0
dtype: int64

In [7]:
df_train = df_train.fillna("NA")

## Solutions

In [8]:
X = df_train.drop(columns=['id', 'target'])
y = df_train['target']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [9]:
X_train

                                            comment_text
29554                                         Fuck life.
44479                                             woooow
28131                                   This so so funny
41042                                                  H
34839                                                 Hi
...                                                  ...
8444        Clark Gable and George Clooney look the same
31718                               The chef is french ?
9697   Pink's reaction would totally be my reaction. ...
37972                                     ONE HOUR LATER
7374              True, demi is better than Taylor swift

[40922 rows x 1 columns]

### CatBoost

In [10]:
model = CatBoostClassifier(
    iterations=50000,
    learning_rate=0.01,
    eval_metric='MultiClass',
    random_seed=42,
    early_stopping_rounds=1000,
    use_best_model=True,
    thread_count=-1,
    task_type='GPU',
    auto_class_weights='Balanced',
    text_features=['comment_text']
)

model.fit(
    X_train,
    y_train,
    eval_set=(X_val, y_val),
    verbose=1000
)

0:	learn: 1.3757865	test: 1.3736073	best: 1.3736073 (0)	total: 7.51ms	remaining: 6m 15s
1000:	learn: 0.6950581	test: 0.6084727	best: 0.6084727 (1000)	total: 3.79s	remaining: 3m 5s
2000:	learn: 0.6369302	test: 0.5734124	best: 0.5734124 (2000)	total: 7.33s	remaining: 2m 55s
3000:	learn: 0.5974888	test: 0.5535477	best: 0.5535477 (3000)	total: 10.8s	remaining: 2m 49s
4000:	learn: 0.5673470	test: 0.5396326	best: 0.5396326 (4000)	total: 14.3s	remaining: 2m 44s
5000:	learn: 0.5421484	test: 0.5283113	best: 0.5283113 (5000)	total: 17.8s	remaining: 2m 40s
6000:	learn: 0.5204663	test: 0.5197035	best: 0.5197035 (6000)	total: 21.4s	remaining: 2m 36s
7000:	learn: 0.5015961	test: 0.5130328	best: 0.5130328 (7000)	total: 24.8s	remaining: 2m 32s
8000:	learn: 0.4850228	test: 0.5074731	best: 0.5074731 (8000)	total: 28.3s	remaining: 2m 28s
9000:	learn: 0.4698110	test: 0.5018543	best: 0.5018543 (9000)	total: 31.9s	remaining: 2m 25s
10000:	learn: 0.4559653	test: 0.4973895	best: 0.4973894 (9999)	total: 35.3s	remaining: 2m 21s
11000:	learn: 0.4434667	test: 0.4932642	best: 0.4932634 (10999)	total: 38.8s	remaining: 2m 17s
12000:	learn: 0.4317335	test: 0.4895386	best: 0.4895386 (12000)	total: 42.3s	remaining: 2m 14s
13000:	learn: 0.4210241	test: 0.4862399	best: 0.4862399 (13000)	total: 45.8s	remaining: 2m 10s
14000:	learn: 0.4109283	test: 0.4832044	best: 0.4832044 (14000)	total: 49.3s	remaining: 2m 6s
15000:	learn: 0.4012037	test: 0.4804072	best: 0.4804072 (15000)	total: 52.8s	remaining: 2m 3s
16000:	learn: 0.3923398	test: 0.4777892	best: 0.4777892 (16000)	total: 56.3s	remaining: 1m 59s
17000:	learn: 0.3837688	test: 0.4753754	best: 0.4753754 (17000)	total: 59.9s	remaining: 1m 56s
18000:	learn: 0.3757944	test: 0.4730314	best: 0.4730300 (17999)	total: 1m 3s	remaining: 1m 52s
19000:	learn: 0.3683040	test: 0.4711278	best: 0.4711278 (19000)	total: 1m 6s	remaining: 1m 49s
20000:	learn: 0.3611113	test: 0.4693367	best: 0.4693367 (20000)	total: 1m 10s	remaining: 1m 45s
21000:	learn: 0.3544551	test: 0.4675258	best: 0.4675219 (20993)	total: 1m 13s	remaining: 1m 42s
22000:	learn: 0.3480004	test: 0.4659338	best: 0.4659338 (22000)	total: 1m 17s	remaining: 1m 38s
23000:	learn: 0.3418045	test: 0.4644905	best: 0.4644879 (22999)	total: 1m 20s	remaining: 1m 35s
24000:	learn: 0.3359101	test: 0.4632205	best: 0.4632170 (23999)	total: 1m 24s	remaining: 1m 31s
25000:	learn: 0.3303454	test: 0.4620429	best: 0.4620429 (25000)	total: 1m 27s	remaining: 1m 27s
26000:	learn: 0.3249886	test: 0.4612346	best: 0.4612239 (25969)	total: 1m 31s	remaining: 1m 24s
27000:	learn: 0.3198104	test: 0.4601721	best: 0.4601714 (26999)	total: 1m 34s	remaining: 1m 20s
28000:	learn: 0.3149013	test: 0.4591132	best: 0.4591019 (27989)	total: 1m 38s	remaining: 1m 17s
29000:	learn: 0.3100095	test: 0.4584083	best: 0.4583797 (28994)	total: 1m 41s	remaining: 1m 13s
30000:	learn: 0.3053365	test: 0.4576070	best: 0.4576070 (30000)	total: 1m 45s	remaining: 1m 10s
31000:	learn: 0.3007852	test: 0.4569137	best: 0.4569063 (30986)	total: 1m 49s	remaining: 1m 6s
32000:	learn: 0.2965109	test: 0.4563941	best: 0.4563875 (31994)	total: 1m 52s	remaining: 1m 3s
33000:	learn: 0.2923909	test: 0.4557374	best: 0.4557374 (33000)	total: 1m 56s	remaining: 59.8s
34000:	learn: 0.2883360	test: 0.4552389	best: 0.4552293 (33989)	total: 1m 59s	remaining: 56.3s
35000:	learn: 0.2843033	test: 0.4546126	best: 0.4546052 (34963)	total: 2m 3s	remaining: 52.8s
36000:	learn: 0.2804257	test: 0.4542395	best: 0.4542359 (35994)	total: 2m 6s	remaining: 49.3s
37000:	learn: 0.2767589	test: 0.4537894	best: 0.4537894 (37000)	total: 2m 10s	remaining: 45.8s
38000:	learn: 0.2731729	test: 0.4533995	best: 0.4533831 (37972)	total: 2m 13s	remaining: 42.3s
39000:	learn: 0.2697265	test: 0.4531416	best: 0.4531416 (38999)	total: 2m 17s	remaining: 38.7s
40000:	learn: 0.2664202	test: 0.4528964	best: 0.4528698 (39956)	total: 2m 20s	remaining: 35.2s
41000:	learn: 0.2631642	test: 0.4526706	best: 0.4526210 (40898)	total: 2m 24s	remaining: 31.7s
42000:	learn: 0.2600166	test: 0.4524079	best: 0.4524062 (41997)	total: 2m 28s	remaining: 28.2s
43000:	learn: 0.2569412	test: 0.4522152	best: 0.4522035 (42898)	total: 2m 31s	remaining: 24.7s
44000:	learn: 0.2538465	test: 0.4519992	best: 0.4519992 (44000)	total: 2m 35s	remaining: 21.1s
45000:	learn: 0.2509491	test: 0.4519068	best: 0.4518533 (44792)	total: 2m 38s	remaining: 17.6s
46000:	learn: 0.2481084	test: 0.4518679	best: 0.4518255 (45933)	total: 2m 42s	remaining: 14.1s
47000:	learn: 0.2453224	test: 0.4517644	best: 0.4517594 (46995)	total: 2m 45s	remaining: 10.6s
48000:	learn: 0.2425970	test: 0.4516348	best: 0.4516107 (47973)	total: 2m 49s	remaining: 7.05s
bestTest = 0.451610702
bestIteration = 47973
Shrink model to first 47974 iterations.

CatBoostClassifier(auto_class_weights='Balanced', early_stopping_rounds=1000, eval_metric='MultiClass', iterations=50000, learning_rate=0.01, random_seed=42, task_type='GPU', text_features=['comment_text'], use_best_model=True)

In [22]:
lm = pd.read_csv('./data/label_mapping.csv')
lm = lm['target_name'].to_dict()
lm

{0: 'ignored', 1: 'applause', 2: 'debate', 3: 'bait'}

In [23]:
df_test.head()

     id                                       comment_text
0   200  Me with Arabic. I can never have a conversatio...
1   607  if I could subscribe to Dude Perfect a million...
2  1100  We can fortunately say that we lived in the er...
3  1137  Not an easy Classic to cover, you and your ban...
4  1139  I really really really love this cover, hope H...

In [24]:
df_test['comment_text'].isna().sum()

np.int64(3)

In [25]:
df_test['comment_text'] = df_test['comment_text'].fillna('NA')

In [26]:
subm = df_test.copy()
subm['pred'] = model.predict(df_test[['comment_text']])
subm.head()

     id                                       comment_text  pred
0   200  Me with Arabic. I can never have a conversatio...     2
1   607  if I could subscribe to Dude Perfect a million...     1
2  1100  We can fortunately say that we lived in the er...     1
3  1137  Not an easy Classic to cover, you and your ban...     1
4  1139  I really really really love this cover, hope H...     1

In [28]:
subm['target'] = subm['pred']
subm[['id', 'target']].to_csv("subm.csv", index=False)
subm.head()

     id                                       comment_text  pred  target
0   200  Me with Arabic. I can never have a conversatio...     2       2
1   607  if I could subscribe to Dude Perfect a million...     1       1
2  1100  We can fortunately say that we lived in the er...     1       1
3  1137  Not an easy Classic to cover, you and your ban...     1       1
4  1139  I really really really love this cover, hope H...     1       1

### Linear Models

#### Data preparing

In [29]:
df_train.head()

    id                                       comment_text  target
0   59  Eh c kii ce favoritisme lui il a tou led iphon...       1
1  167  It's a myth that Neanderthals were stupid. The...       1
2  169             Emma is super white.\nIn other news...       1
3  372  Chelsea and Aubrey are my favourite on Teen Mo...       1
4  373  that mustard colour tho 😻😻 p.s absolutely love...       1